**4 TO - DO - Task**

**4.1. Exercise on Functions:**

Task - 1: Create a Python program that converts between different units of measurement.

In [1]:
def convert_units(conversion_type, value):
    """
    Convert units between length, weight, and volume.

    Parameters:
    conversion_type (str): Type of conversion
    value (float): Value to convert

    Returns:
    float: Converted value
    """

    if conversion_type == "m_to_ft":
        return value * 3.28084
    elif conversion_type == "ft_to_m":
        return value / 3.28084
    elif conversion_type == "kg_to_lbs":
        return value * 2.20462
    elif conversion_type == "lbs_to_kg":
        return value / 2.20462
    elif conversion_type == "l_to_gal":
        return value * 0.264172
    elif conversion_type == "gal_to_l":
        return value / 0.264172
    else:
        raise ValueError("Unsupported conversion type")


def unit_converter():
    try:
        print("Choose conversion type:")
        print("1: meters → feet")
        print("2: feet → meters")
        print("3: kg → pounds")
        print("4: pounds → kg")
        print("5: liters → gallons")
        print("6: gallons → liters")

        choice = input("Enter choice: ")
        value = float(input("Enter value to convert: "))

        mapping = {
            "1": "m_to_ft",
            "2": "ft_to_m",
            "3": "kg_to_lbs",
            "4": "lbs_to_kg",
            "5": "l_to_gal",
            "6": "gal_to_l"
        }

        result = convert_units(mapping[choice], value)
        print("Converted value:", result)

    except Exception as e:
        print("Error:", e)


unit_converter()

Choose conversion type:
1: meters → feet
2: feet → meters
3: kg → pounds
4: pounds → kg
5: liters → gallons
6: gallons → liters
Enter choice: 1
Enter value to convert: 1.80
Converted value: 5.905512


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.

In [2]:
def calculate_sum(numbers):
    """Return sum of numbers."""
    return sum(numbers)

def calculate_average(numbers):
    """Return average of numbers."""
    return sum(numbers) / len(numbers)

def find_max(numbers):
    """Return maximum number."""
    return max(numbers)

def find_min(numbers):
    """Return minimum number."""
    return min(numbers)


def list_operations():
    try:
        numbers = list(map(float, input("Enter numbers separated by space: ").split()))

        if len(numbers) == 0:
            raise ValueError("List cannot be empty")

        print("Choose operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")

        choice = input("Enter choice: ")

        if choice == "1":
            print("Sum:", calculate_sum(numbers))
        elif choice == "2":
            print("Average:", calculate_average(numbers))
        elif choice == "3":
            print("Maximum:", find_max(numbers))
        elif choice == "4":
            print("Minimum:", find_min(numbers))
        else:
            print("Invalid choice")

    except Exception as e:
        print("Error:", e)


list_operations()

Enter numbers separated by space: 1 2 3 4 5
Choose operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice: 1
Sum: 15.0


**4.2 Exercise on List Manipulation:**

1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.

In [5]:
lst = [1,2,3,4,5,6]

def extract_every_other(lst):
    return lst[::2]

print(extract_every_other(lst))

[1, 3, 5]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

In [6]:
lst = [1,2,3,4,5,6]

def get_sublist(lst, start, end):
    return lst[start:end+1]

print(get_sublist(lst,2,4))

[3, 4, 5]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.

In [10]:
lst = [1,2,3,4,5]

def reverse_list(lst):
    return lst[::-1]

print(reverse_list(lst))

[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting sublist.

In [11]:
lst = [1,2,3,4,5]

def remove_first_last(lst):
    return lst[1:-1]

print(remove_first_last(lst))

[2, 3, 4]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.

In [12]:
lst = [1,2,3,4,5]

def get_first_n(lst, n):
    return lst[:n]

print(get_first_n(lst,3))

[1, 2, 3]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.

In [13]:
lst = [1,2,3,4,5]

def get_last_n(lst, n):
    return lst[-n:]

print(get_last_n(lst,2))

[4, 5]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

In [14]:
lst = [1,2,3,4,5,6]

def reverse_skip(lst):
    return lst[-2::-2]

print(reverse_skip(lst))

[5, 3, 1]


**4.3 Exercise on Nested List:**
1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

In [16]:
lst = [[1, 2], [3, 4], [5]]

def flatten(lst):
    result = []
    for sub in lst:
        if isinstance(sub, list):
            result.extend(sub)
        else:
            result.append(sub)
    return result

flatten(lst)

[1, 2, 3, 4, 5]

2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.

In [17]:
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1,2]

def access_nested_element(lst, indices):
    element = lst
    for i in indices:
        element = element[i]
    return element

access_nested_element(lst, indices)

6

3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [18]:
lst = [[1, 2], [3, [4, 5]], 6]

def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

sum_nested(lst)

21

4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.

In [19]:
lst = [[1, 2], [3, 2], [4, 5]]
elem = 2

def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        else:
            if item != elem:
                result.append(item)
    return result

remove_element(lst, elem)

[[1], [3], [4, 5]]

5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).

In [21]:
lst = [[1, 2], [3, [4, 5]], 6]

def find_max(lst):
    maximum = float('-inf')
    for item in lst:
        if isinstance(item, list):
            maximum = max(maximum, find_max(item))
        else:
            maximum = max(maximum, item)
    return maximum

find_max(lst)

6

6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.

In [22]:
lst = [[1, 2], [2, 3], [2, 4]]
elem = 2

def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1
    return count

count_occurrences(lst, elem)

3

7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [23]:
lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

deep_flatten(lst)

[1, 2, 3, 4, 5, 6, 7, 8]

8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.

In [24]:
lst =  [[1, 2], [3, 4], [5, 6]]

def average_nested(lst):
    flat = deep_flatten(lst)
    return sum(flat)/len(flat)

average_nested(lst)

3.5

**10 To - Do - NumPy**

**10.1 Basic Vector and Matrix Operation with Numpy.**

Problem - 1: Array Creation:

Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [27]:
import numpy as np

# 1
a = np.empty((2,2))

print(a)

[[1.45012201e-315 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


In [28]:
import numpy as np

# 2
b = np.ones((4,2))

print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [29]:
import numpy as np

# 3
c = np.full((3,3),7)

print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [30]:
import numpy as np

# 4
d = np.zeros_like(b)

print(d)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [31]:
import numpy as np

# 5
e = np.ones_like(b)

print(e)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [33]:
import numpy as np

# 6
new_list = [1,2,3,4]
f = np.array(new_list)

print(f)

[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [34]:
import numpy as np

# 1
arr = np.arange(10,50)

print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [35]:
import numpy as np

# 2
matrix = np.arange(9).reshape(3,3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [36]:
import numpy as np

# 3
identity = np.eye(3)

print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
import numpy as np

# 4
rand_arr = np.random.random(30)
mean_val = rand_arr.mean()

print(mean_val)

0.4514418903622015


In [39]:
import numpy as np

# 5
rand_10 = np.random.random((10,10))
min_val = rand_10.min()
max_val = rand_10.max()

print(min_val)
print(max_val)

0.012670950480339949
0.9946112959091975


In [41]:
import numpy as np

# 6
z = np.zeros(10)
z[4] = 1

print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [42]:
import numpy as np

# 7
arr2 = np.array([1,2,0,0,4,0])
rev = arr2[::-1]

print(rev)

[0 4 0 0 2 1]


In [43]:
import numpy as np

# 8
border = np.ones((5,5))
border[1:-1,1:-1] = 0

print(border)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [44]:
import numpy as np

# 9
checker = np.zeros((8,8))
checker[1::2,::2] = 1
checker[::2,1::2] = 1

print(checker)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [50]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1
print(x + y)
print("\n")
print(v + w)

[[ 6  8]
 [10 13]]


[20 22]


In [52]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 2
print(x - y)
print("\n")
print(v - w)

[[-4 -4]
 [-4 -3]]


[-2 -2]


In [53]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 3
print(x * 3)

[[ 3  6]
 [ 9 15]]


In [54]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 4
print(np.square(x))

[[ 1  4]
 [ 9 25]]


In [55]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 5
print(np.dot(v,w))
print(np.dot(x,v))
print(np.dot(x,y))

219
[29 77]
[[19 22]
 [50 58]]


In [56]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 6
print(np.concatenate((x,y), axis=0))
print(np.concatenate((v,w), axis=0))

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[ 9 10 11 12]


In [57]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 7
try:
    print(np.concatenate((x,v)))
except Exception as e:
    print("Error:", e)
    print("Explanation: dimensions do not match")

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: dimensions do not match


Problem - 4: Matrix Operations:

For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:

1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)T = BTAT

In [61]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1  A * A^-1
A_inv = np.linalg.inv(A)
print(np.dot(A, A_inv))

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [62]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 2  AB != BA
print("AB =\n", np.dot(A,B))
print("BA =\n", np.dot(B,A))

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]


In [63]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 3 (AB)^T = B^T A^T
left = np.transpose(np.dot(A,B))
right = np.dot(np.transpose(B), np.transpose(A))

print(left)
print(right)

[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [64]:
A = np.array([
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
])

B = np.array([-1,-3,9])

# Using inverse
A_inv = np.linalg.inv(A)
X = np.dot(A_inv,B)

print("Solution:",X)

Solution: [ 2.  1. -2.]


**10.2 Experiment: How Fast is Numpy?**

1. Element-wise Addition:

In [65]:
import numpy as np
import time

size = 1000000

a = list(range(size))
b = list(range(size))

start = time.time()
result = [a[i] + b[i] for i in range(size)]
print("Python addition time:", time.time()-start)

a_np = np.array(a)
b_np = np.array(b)

start = time.time()
result = a_np + b_np
print("Numpy addition time:", time.time()-start)

Python addition time: 0.11544513702392578
Numpy addition time: 0.01812577247619629


2. Element-wise Multiplication

In [66]:
import numpy as np
import time

start = time.time()
result = [a[i]*b[i] for i in range(size)]
print("Python multiplication:", time.time()-start)

start = time.time()
result = a_np * b_np
print("Numpy multiplication:", time.time()-start)

Python multiplication: 0.1275482177734375
Numpy multiplication: 0.01783132553100586


3. Dot Product

In [67]:
import numpy as np
import time

start = time.time()
dot = sum(a[i]*b[i] for i in range(size))
print("Python dot:", time.time()-start)

start = time.time()
dot = np.dot(a_np,b_np)
print("Numpy dot:", time.time()-start)

Python dot: 0.11648964881896973
Numpy dot: 0.0018663406372070312


4. Matrix Multiplication

In [68]:
import numpy as np
import time

size = 1000

A = np.random.rand(size,size)
B = np.random.rand(size,size)

start = time.time()
C = np.dot(A,B)
print("Numpy matrix multiplication:", time.time()-start)

Numpy matrix multiplication: 0.06823921203613281
